### ISSUE TITLE
当空间相册过多时 只能获取到前30个

### ISSUE THREAD

**Issue by kmakise** [dslwind/qzone-photo-downloader#3]
我在使用这个程序获取空间相册列表的时候发现只能获取到前三十个，使用网页打开时默认也是加载前三十个，如果页面没有滚动动作的时候无法加载全部的相册

**Comment by dslwind** [comment]
定位到downloader.py 110行，应该是这里的几个数字控制的
'&notice=0&filter=1&handset=4&pageNumModeSort=40&pageNumModeClass=15&needUserInfo=1'

**Comment by kmakise** [comment]
都修改尝试过了 还是只能获取到前三十个，requests.get后能否模拟滚动一下来加载后面的相册

**Comment by dslwind** [comment]
> 都修改尝试过了 还是只能获取到前三十个，requests.get后能否模拟滚动一下来加载后面的相册

可以尝试用浏览器的调试工具，network项，过滤list_album，看看有哪些变化

**Comment by dslwind** [comment]
> 
> 
> 都修改尝试过了 还是只能获取到前三十个，requests.get后能否模拟滚动一下来加载后面的相册

找了一个好友的空间测试了一下，把`pageNumModeClass=15`修改为`pageNumModeClass=999`可以获取完整列表。

**Comment by hupo376787** [comment]
改成999测试了，无效
