### ISSUE TITLE
最大下载数目为500

### ISSUE THREAD

**Issue by shiyuwang1110** [dslwind/qzone-photo-downloader#5]
相册里的照片数目超过500张，但是下载下来的照片只有500张。
不知道是为什么

**Comment by zhufeng** [comment]
确实是有这个问题

**Comment by Spico197** [comment]
可以修改`photobase`中的`pageStart`参数，一页下载完之后跳下一页

**Comment by zq99299** [comment]
该问题已修复
pr 还未合并之前，可以使用我仓库的代码：https://github.com/zq99299/qzone-photo-downloader

**Comment by dslwind** [comment]
pr已合并
